routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');


Route::get('/lang/{locale?}', [
    'as'=>'lang',
    'uses'=>'HomeController@changeLang'
]);

Route::group(['middleware' => ['role:root']], function () {


    // Role Route
    Route::resource('roles', 'RoleController');

    // Role Route
    Route::resource('permissions', 'PermissionController');


});


// Users Route
Route::resource('users', 'UserController');

// Projects Route
Route::resource('projects', 'ProjectController');

// Tasks Route
Route::resource('tasks', 'TaskController');

// Times Route
Route::resource('times', 'TimeController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;


class Project extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'project_status_id', 'start_at', 'end_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];


    /**
     * Get the post that owns the comment.
     */
    public function project_status()
    {
        return $this->belongsTo('App\ProjectStatus');

    }

    public function project_types()
    {
        return $this->belongsToMany('App\ProjectType');
    }

    public function client()
    {
        return $this->belongsTo('App\Client');

    }
}

app/ProjectType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProjectType extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'project_types';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'color'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];


}

app/ProjectTypes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProjectTypes extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'project_project_type';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'project_id', 'project_type_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use App\Time;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\DatabaseManager;
use Spatie\Permission\Models\Role;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use App\Notifications\UserCreated;
use App\User;
use App\Client;
use App\Project;
use App\ProjectTypes;
use App\ProjectStatus;
use App\ProjectType;
use App\TaskStatus;
use App\TaskType;
use Carbon\Carbon;


class ProjectController extends Controller
{

    use Notifiable;



    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the project dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        // Get all roles
        $projects = Project::all();

        // View roles' index view
        return view('projects.index')->with('projects', $projects);

    }

    /**
     * Show the project details.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        // Get project details
        $project = Project::findOrFail($id);
        $task_statuses = TaskStatus::all();
        $task_types = TaskType::all();
        $users = User::all();
        $tasks = Task::where('project_id', $id)->get();
        $times = DB::table('times')
            ->leftjoin('tasks', 'times.task_id', '=', 'tasks.id')
            ->leftjoin('projects', 'tasks.project_id', '=', 'projects.id')
            ->leftjoin('users', 'times.user_id', '=', 'users.id')
            ->select('users.name as name', DB::raw('SUM(times.seconds) as spent'))
            ->where('project_id', $id)
            ->groupBy('users.name')
            ->get();

        $total = DB::table('times')
            ->leftjoin('tasks', 'times.task_id', '=', 'tasks.id')
            ->leftjoin('projects', 'tasks.project_id', '=', 'projects.id')
            ->leftjoin('users', 'times.user_id', '=', 'users.id')
            ->select(DB::raw('SUM(times.seconds) as spent') )
            ->where('project_id', $id)
            ->get();


        // View roles' index view
        return view('projects.view', compact('project','task_statuses','task_types','users','tasks', 'times', 'total'));


    }


    /**
     * Create project.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {

        $clients = Client::all();
        $project_statuses = ProjectStatus::all();
        $project_types = ProjectType::all();

        return view('projects.create', compact('project_statuses', 'project_types','clients'));
    }


    /**
     * Store project.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        //Validate name and permissions field
        $this->validate($request, [
                'project_status'=>'required',
                'name'=>'required',
                'start_at'=>'required'
            ]
        );

        // Begin transaction
        DB::beginTransaction();

        // Create project
        $project = new Project();
        $project->name              = $request['name'];
        $project->description       = $request['description'];
        $project->project_status_id = $request['project_status'];
        $project->client_id         = $request['project_client'];
        $project->start_at          = Carbon::createFromFormat('d-m-Y', $request['start_at'])->toDateString();
        $project->end_at            = Carbon::createFromFormat('d-m-Y', $request['end_at'])->toDateString();
        $create = $project->save();
        if(!$create){ DB::rollBack(); }


        // Foreach types
        $project_types = $request['project_types'];
        foreach ($project_types as $project_type) {
            $project_has_types = new ProjectTypes();
            $project_has_types->timestamps = false;
            $project_has_types->project_id      = $project->id;
            $project_has_types->project_type_id = $project_type;
            $create = $project_has_types->save();
            if(!$create){ DB::rollBack(); }
        }

        // DB Commit
        DB::commit();

        return redirect()->route('projects.index')
            ->with('success',
                'Project '. $project->name.' added!');
    }


    /**
     * Destroy project.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Project::findOrFail($id);
        $project->delete();

        return redirect()->route('projects.index')
            ->with('success',
                'Project '.$project->name.' deleted!');

    }

    /**
     * Update role.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {


        $project = Project::findOrFail($id);//Get role with the given id

        //Validate name and permissions field
        $this->validate($request, [
                'project_status'=>'required',
                'name'=>'required',
                'start_at'=>'required'
            ]
        );

        // Begin transaction
        DB::beginTransaction();

        // Save
        $project->name              = $request['name'];
        $project->description       = $request['description'];
        $project->project_status_id = $request['project_status'];
        $project->client_id         = $request['project_client'];
        $project->start_at          = Carbon::createFromFormat('d-m-Y', $request['start_at'])->toDateString();
        $project->end_at            = Carbon::createFromFormat('d-m-Y', $request['end_at'])->toDateString();
        $save = $project->save();

        if(!$save){ DB::rollBack(); }

        // Remove types relations
        $delete = DB::table('project_project_type')->where('project_id', $id)->delete();
        if(!$delete){ DB::rollBack(); }


        // Foreach types
        $project_types = $request['project_types'];
        foreach ($project_types as $project_type) {
            $project_has_types = new ProjectTypes();
            $project_has_types->timestamps = false;
            $project_has_types->project_id      = $project->id;
            $project_has_types->project_type_id = $project_type;
            $save = $project_has_types->save();
            if(!$save){ DB::rollBack(); }
        }

        // DB Commit
        DB::commit();

        return redirect()->route('projects.index')
            ->with('success',
                'Project: '. $project->name.' updated!');
    }


    /**
     * Update role.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {

        $project = Project::findOrFail($id);
        $project_statuses = ProjectStatus::all();
        $project_types = ProjectType::all();
        $ppt = ProjectTypes::all()->where('project_id', $id)->pluck('project_type_id')->toArray();
        $clients = Client::all();


        return view('projects.edit', compact('project', 'project_statuses', 'project_types', 'ppt', 'clients'));
    }


}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                @include('flash-message')
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{_i('Nuevo proyecto')}}</h3>
                    </div>
                    <div class="panel-body">

                        {{ Form::open(['url' => Route('projects.store'), 'method' => 'post', 'class' => 'form-horizontal']) }}


                        <div class="form-group">
                            <label for="project_client" class="col-sm-2 control-label">{{ _i('Cliente') }}</label>
                            <div class="col-sm-10">
                                <select id="project_client" name="project_client" class="form-control">
                                    <option selected="selected">-- Seleccione Cliente --</option>
                                    @foreach($clients as $client)
                                        <option value="{{ $client->id }}"> {{ $client->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="project_types" class="col-sm-2 control-label">{{ _i('Tipo') }}</label>
                            <div class="col-sm-10">
                                <select multiple id="project_types" name="project_types[]" class="form-control">
                                    <option selected="selected">-- Seleccione Tipo --</option>
                                    @foreach($project_types as $project_type)
                                        <option value="{{ $project_type->id }}"> {{ $project_type->title }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputStatus" class="col-sm-2 control-label">{{ _i('Estado') }}</label>
                            <div class="col-sm-10">
                                <select id="inputStatus" name="project_status" class="form-control">
                                    <option selected="selected">-- Seleccione Estado --</option>
                                    @foreach($project_statuses as $project_status)
                                        <option value="{{ $project_status->id }}"> {{ $project_status->title }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">{{ _i('Nombre') }}</label>
                            <div class="col-sm-10">
                                <input type="text" name="name" class="form-control" id="inputName" placeholder="{{ _i('Nombre') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputDesc" class="col-sm-2 control-label">{{ _i('Descripción') }}</label>
                            <div class="col-sm-10">
                                <input type="text" name="description" class="form-control" id="inputDesc" placeholder="{{ _i('Descripción del proyecto') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputStart" class="col-sm-2 control-label">{{ _i('Fecha de inicio') }}</label>
                            <div class="col-sm-10">
                                <input type="text" name="start_at" class="form-control" id="inputStart" placeholder="{{ _i('Nombre') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEnd" class="col-sm-2 control-label">{{ _i('Fecha de finalización') }}</label>
                            <div class="col-sm-10">
                                <input type="text" name="end_at" class="form-control" id="inputEnd" placeholder="{{ _i('Nombre') }}">
                            </div>
                        </div>


                        @if(auth()->user()->can('create project') || auth()->user()->role('root'))
                            {{ Form::submit(_i('Crear'), array('class' => 'btn btn-success')) }}
                        @endif


                        {{ Form::close() }}

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>


                </div>
            </div>

        </div>
    </div>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                @include('flash-message')
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ $project->name }}</h3>
                    </div>
                    <div class="panel-body">

                        {{ Form::model($project, array('route' => array('projects.update', $project->id), 'method' => 'PUT', 'class' => 'form-horizontal')) }}



                        <div class="form-group">
                            <label for="project_client" class="col-sm-2 control-label">{{ _i('Cliente') }}</label>
                            <div class="col-sm-10">
                                <select id="project_client" name="project_client" class="form-control">
                                    <option>-- Seleccione Cliente --</option>
                                    @foreach($clients as $client)
                                        @if($client->id == $project->client_id)
                                            <option value="{{ $client->id }}" selected="selected"> {{ $client->name }}</option>
                                        @else
                                            <option value="{{ $client->id }}"> {{ $client->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="project_types" class="col-sm-2 control-label">{{ _i('Tipo') }}</label>
                            <div class="col-sm-10">
                                <select multiple id="project_types" name="project_types[]" class="form-control">
                                    @foreach($project_types as $project_type)

                                        @if(in_array($project_type->id, $ppt))
                                            <option value="{{ $project_type->id }}" selected="selected"> {{ $project_type->title }}</option>
                                        @else
                                            <option value="{{ $project_type->id }}"> {{ $project_type->title }}</option>
                                        @endif

                                    @endforeach
                                </select>
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="inputStatus" class="col-sm-2 control-label">{{ _i('Estado') }}</label>
                            <div class="col-sm-10">
                                <select id="inputStatus" name="project_status" class="form-control">
                                    <option selected="selected">-- Seleccione Estado --</option>
                                    @foreach($project_statuses as $project_status)
                                        @if($project_status->id == $project->project_status_id)
                                            <option value="{{ $project_status->id }}" selected="selected"> {{ $project_status->title }}</option>
                                        @else
                                            <option value="{{ $project_status->id }}"> {{ $project_status->title }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputName" class="col-sm-2 control-label">{{ _i('Nombre') }}</label>
                            <div class="col-sm-10">
                                <input type="text" name="name" value="{{  $project->name }}" class="form-control" id="inputName" placeholder="{{ _i('Nombre') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputDesc" class="col-sm-2 control-label">{{ _i('Descripción') }}</label>
                            <div class="col-sm-10">
                                <input type="text" name="description" value="{{  $project->description }}" class="form-control" id="inputDesc" placeholder="{{ _i('Descripción del proyecto') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputStart" class="col-sm-2 control-label">{{ _i('Fecha de inicio') }}</label>
                            <div class="col-sm-10">
                                <input type="text" name="start_at" value="{{  Carbon\Carbon::parse($project->start_at)->format('d-m-Y') }}" class="form-control" id="inputStart" placeholder="{{ _i('Nombre') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEnd" class="col-sm-2 control-label">{{ _i('Fecha de finalización') }}</label>
                            <div class="col-sm-10">
                                <input type="text" name="end_at" value="{{  Carbon\Carbon::parse($project->end_at)->format('d-m-Y') }}" class="form-control" id="inputEnd" placeholder="{{ _i('Nombre') }}">
                            </div>
                        </div>


                        @if(auth()->user()->can('edit project') || auth()->user()->role('root'))
                            {{ Form::submit(_i('Editar'), array('class' => 'btn btn-success')) }}
                        @endif


                        {{ Form::close() }}

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>


                </div>
            </div>

        </div>
    </div>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                @include('flash-message')
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ _i('Proyectos') }}</h3>
                    </div>
                    <div class="panel-body">

                        <div>

                            <div class="col-md-12" style="margin-bottom:15px;">
                                <a href="{{Route('projects.create')}}" class="btn btn-xs btn-default"><i class="fas fa-user"></i> {{ _i('Nuevo Proyecto') }}</a>
                            </div>

                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>{{ _i('Estado') }}</th>
                                    <th>{{ _i('Proyecto') }}</th>
                                    <th>{{ _i('Descripción') }}</th>
                                    <th>{{ _i('Tags') }}</th>
                                    <th>{{ _i('Acciones') }}</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach($projects as $project)

                                    <tr>
                                        <td><span class="label" style="background-color:{{$project->project_status->color}};">{{ $project->project_status->title }}</span></td>
                                        <td>{{ $project->name }}</td>
                                        <td>{{ $project->description }}</td>
                                        <td>

                                            @if(count($project->project_types) > 0)

                                                @foreach($project->project_types as $type)
                                                    <span class="label" style="background-color:{{$type->color}};">{{ $type->title }}</span>
                                                @endforeach

                                            @else
                                                <span class="label label-info">Sin tags asociados.</span>
                                            @endif

                                        </td>
                                        <td>

                                            <a href="{{ route('projects.show', $project->id) }}" class="btn btn-xs btn-warning pull-left" style="margin-right: 3px;">{{ _i('Ver') }}</a>
                                            <a href="{{ route('projects.edit', $project->id) }}" class="btn btn-xs btn-info pull-left" style="margin-right: 3px;">{{ _i('Editar') }}</a>

                                            {!! Form::open(['method' => 'DELETE', 'route' => ['projects.destroy', $project->id] ]) !!}
                                            {!! Form::submit( _i('Borrar'), ['class' => 'btn btn-xs btn-danger']) !!}
                                            {!! Form::close() !!}

                                        </td>
                                    </tr>

                                @endforeach

                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection